---
title: "Data Manipulation and cleaning"
author: "Yunshen Bai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup,message=FALSE,warning=FALSE}
library(tidyverse)
library(rvest)
library(httr)

```

## source 1:corruption index

```{r,message=FALSE,warning=FALSE}
corruption=read_csv("C:/Users/Leon/Desktop/p8105_final_project/data/corruption_index.csv")|>
  janitor::clean_names()|>
  mutate(value=(as.numeric(x2020_yr2020)+as.numeric(x2020_yr2020)+as.numeric(x2020_yr2020))/3)|>
  select(country_name,country_code,series_name,value)|>
  pivot_wider(
    names_from = "series_name",
    values_from = "value"
  )|>
  janitor::clean_names()
```

## source 2: country code
```{r}
isso_code=
  read_html("https://www.countrycode.org/")|>
  html_elements("td:nth-child(3)")|>
  html_text()

country_name_isso=
  read_html("https://www.countrycode.org/")|>
  html_elements("td:nth-child(1)")|>
  html_text()

country_code=data.frame(country_name_isso,str_split_fixed(isso_code, '/',2))|>
  rename(c(country_code_2=X1,country_code_3=X2))|>
  mutate(country_code_2=gsub('[ ]','',country_code_2),
         country_code_3=gsub('[ ]','',country_code_3))|>
  distinct(country_code_3, .keep_all = T)
```

## sourse 3:GDP

```{r,message=FALSE}
GDP=read_csv("./data/GDP.csv")|>
  janitor::clean_names()|>
  filter(average_gdp!="#DIV/0!")|>
  mutate(GDP=as.numeric(average_gdp))|>
  select(country_name,country_code,GDP)|>
  mutate(GDP=GDP/10^9)
```

## source 4:continent
```{r}
Africa=
  read_html("https://www.countrycallingcodes.com/iso-country-codes/africa-codes.php") |>
  html_elements("tr+ tr td:nth-child(3) font") |>
  html_text()

Asia=
  read_html("https://www.countrycallingcodes.com/iso-country-codes/asia-codes.php") |>
  html_elements("tr+ tr td:nth-child(3) font") |>
  html_text()

Europe=
  read_html("https://www.countrycallingcodes.com/iso-country-codes/europe-codes.php") |>
  html_elements("tr+ tr td:nth-child(3) font") |>
  html_text()|>
  append("JEY")

North_America=
  read_html("https://www.countrycallingcodes.com/iso-country-codes/north-america-codes.php") |>
  html_elements("tr+ tr td:nth-child(3) font") |>
  html_text()

South_America=
  read_html("https://www.countrycallingcodes.com/iso-country-codes/south-america-codes.php") |>
  html_elements("tr+ tr td:nth-child(3) font") |>
  html_text()

Oceania=
  read_html("https://www.countrycallingcodes.com/iso-country-codes/australia-codes.php") |>
  html_elements("tr+ tr td:nth-child(3) font") |>
  html_text()

Antarctica=
  read_html("https://www.countrycallingcodes.com/iso-country-codes/antarctica-codes.php") |>
  html_elements("tr+ tr td:nth-child(3) font") |>
  html_text()
```



## source 5: developed/developing

```{r,message=FALSE}
developed=
  read_csv("C:/Users/Leon/Desktop/p8105_final_project/data/developed-countries-2023.csv")|>
  pull(cca3)
least_develpoed=
  read_csv("C:/Users/Leon/Desktop/p8105_final_project/data/least-developed-countries-2023.csv")|>
  pull(cca3)
```

## source 6: coordinate
```{r}
coordinate_html=
  read_html("https://developers.google.com/public-data/docs/canonical/countries_csv?hl=en")

country_name=
  coordinate_html |>
  html_elements("td:nth-child(4)") |>
  html_text()

country_code2=
  coordinate_html |>
  html_elements("td:nth-child(1)") |>
  html_text() 

latitude=
  coordinate_html |>
  html_elements("td:nth-child(2)") |>
  html_text()

longitude=
  coordinate_html |>
  html_elements("td:nth-child(3)") |>
  html_text()

country_coordinate=
  data.frame(country_name,country_code2,latitude,longitude)|>
  left_join(country_code,join_by(country_code2==country_code_2))|>
  select(country_name,country_code=country_code_3,latitude,longitude)
```

## source 7: population

```{r,message=FALSE}
population=read_csv("./data/population.csv")|>
  janitor::clean_names()|>
  select(country_name,country_code,x1996:x2022)|>
  pivot_longer(
    x1996:x2022,
    names_to = "year",
    values_to = "population")|>
  mutate(year=substr(year,2,5))
```


## overall dataset
```{r}
corruption_data=left_join(corruption,country_code,join_by(country_code==country_code_3))|>
  left_join(GDP,join_by(country_code==country_code))|>
  left_join(country_coordinate,join_by(country_code_2==country_code))|>
  mutate(development=case_when(
    country_code %in% developed ~ "Developed",
    country_code %in% least_develpoed ~ "Least Developed",
    (!country_code %in% developed) & (!country_code %in% least_develpoed) ~ "Developing"
  ))|>
  mutate(continent=case_when(
    country_code %in% Asia ~ "Asia",
    country_code %in% Africa ~ "Africa",
    country_code %in% Europe ~ "Europe",
    country_code %in% North_America ~ "North America",
    country_code %in% South_America ~ "South America",
    country_code %in% Oceania ~ "Oceania",
    country_code %in% Antarctica ~ "Antarctica"
  ))|>
  select(country_name,
         corruption_index=control_of_corruption_estimate,
         government_effectiveness=government_effectiveness_estimate,
         political_stability_and_absence_of_violence_terrorism=political_stability_and_absence_of_violence_terrorism_estimate,
         regulatory_quality=regulatory_quality_estimate,
         rule_of_law=rule_of_law_estimate,
         voice_and_accountability=voice_and_accountability_estimate,
         GDP,latitude,longitude,development,continent)
```


```{r,message=FALSE}
corruption_EDA_pre=read_csv("C:/Users/Leon/Desktop/p8105_final_project/data/corruption_index.csv")|>
  janitor::clean_names()|>
  pivot_longer(
    cols = x1996_yr1996:x2022_yr2022,
    names_to = "year",
    values_to = "value"
  )|>
  mutate(year=substr(year,2,5))|>
  select(-series_code)|>
  pivot_wider(
    names_from = "series_name",
    values_from = "value"
  )

GDP_EDA=
  read_csv("./data/GDP.csv")|>
  janitor::clean_names()|>
  select(country_code,x1996:x2022)|>
  pivot_longer(
    x1996:x2022,
    names_to = "year",
    values_to = "GDP"
               )|>
  mutate(GDP=GDP/10^9,
         year=substr(year,2,5))

corruption_EDA=
  corruption_EDA_pre|>
  left_join(GDP_EDA,by = join_by(country_code, year))|>
  janitor::clean_names()|>
  select(country_name,country_code,year,
         corruption_index=control_of_corruption_estimate,
         government_effectiveness=government_effectiveness_estimate,
         political_stability_and_absence_of_violence_terrorism=political_stability_and_absence_of_violence_terrorism_estimate,
         regulatory_quality=regulatory_quality_estimate,
         rule_of_law=rule_of_law_estimate,
         voice_and_accountability=voice_and_accountability_estimate,
         gdp)|>
  mutate(continent=case_when(
    country_code %in% Asia ~ "Asia",
    country_code %in% Africa ~ "Africa",
    country_code %in% Europe ~ "Europe",
    country_code %in% North_America ~ "North America",
    country_code %in% South_America ~ "South America",
    country_code %in% Oceania ~ "Oceania",
    country_code %in% Antarctica ~ "Antarctica"
  ))|>
  mutate(development=case_when(
    country_code %in% developed ~ "Developed",
    country_code %in% least_develpoed ~ "Least Developed",
    (!country_code %in% developed) & (!country_code %in% least_develpoed) ~ "Developing"
  ))|>
    left_join(country_coordinate,join_by(country_code))|>
  left_join(population,join_by(country_code,year))|>
  select(country_name=country_name.x,everything(),-country_name.y,-country_name)
  
write.table(corruption_EDA,"./data/corruption_EDA.csv",row.names=FALSE,col.names=TRUE,sep=",")

```



