---
title: "Data Manipulation and cleaning"
author: "Kindle zhang"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: "hide"
    css: styles.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, 
  message = FALSE, 
  echo = TRUE,
  fig.width = 6,
  fig.asp = 0.4,
  out.width = "90%")
library(tidyverse)
library(rvest)
library(httr)
library(readxl)

library(ggplot2)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
isso_code =
  read_html("https://www.countrycode.org/") |>
  html_elements("td:nth-child(3)") |>
  html_text()

country_name_isso =
  read_html("https://www.countrycode.org/") |>
  html_elements("td:nth-child(1)") |>
  html_text()

country_code = 
  data.frame(country_name_isso, str_split_fixed(isso_code, '/', 2)) |>
  rename(c(country_code_2 = X1, country_code_3 = X2)) |>
  mutate(
    country_code_2 = gsub('[ ]', '', country_code_2),
    country_code_3 = gsub('[ ]', '', country_code_3)
  ) |>
  distinct(country_code_3, .keep_all = T)
```

```{r}
country_code = 
  country_code |> 
    select(-country_code_2) |>
    rename("Country / Territory" = country_name_isso,
           "Country code" = country_code_3)
```

```{r}

numberlist = c("A1:M200", "N1:P200", "Q1:S200", "T1:V200", "W1:Y200", "Z1:AB200", "AC1:AE200", "AF1:AH200", "AI1:AK200", "AL1:AN200", "AO1:AQ200", "AR1:AT200", "AU1:AW200", "AX1:AZ200", "BA1:BC200")



read_cpi = 
  function(address, scope){
    tidy_data = 
  read_excel(address, sheet = 1, scope)
    
    tidy_data
}
```



```{r}
for (i in 1:length(numberlist)){

  tidy_data = 
    read_cpi("./data/Country CPI 1998-2022.xlsx",
            numberlist[[i]]) 
  
  country_code = 
    country_code |> 
    left_join(tidy_data, by = "Country / Territory")
}
```

```{r, warning = FALSE}
country_code = 
    country_code |>
    select("Country / Territory", "Country code.x", contains(c("20", "19"))) |> 
  janitor::clean_names() |> 
  rename("country_code" = country_code_x)

names(country_code) = 
  gsub("cpi_score_", "", names(country_code))

country_code$"2005" = as.numeric(country_code$"2005")

cols_to_check =  as.character(c(1998 : 2022))

country_code =
  country_code |> 
  select(sort(names(country_code))) |> 
  relocate(country_territory, country_code)|> 
  mutate_at(vars(c("1998":"2011")), ~ . * 10) |> 
  filter(!if_all(cols_to_check, is.na))
```

```{r}
country_code |> 
  write.table(
    file = "./data/cleaned_data/cpi_data_year.csv",
    sep = ",", 
    row.names = FALSE)
```

